# Decision Tree + Random forest with and without lib

+ #### Import lib
+ ###### panda to data processing
+ ###### numpy to handel with matrix
+ ###### categori_encoder to handel with object type
+ ###### split_dataset to spit dataset to test and train file
+ ###### scaler to standardize transform dataset
+ ###### r2_score to calc R-squared score
+ ###### accuracy_metric to score accuracy
+ ###### CART_tree to get CART model

In [1]:
import pandas as pd
import numpy as np
import CART_tree #local file
import split_dataset as sp #local file
import scaler
import r2_score #local file
import categori_encoder as ce # local file
import accuracy_metric #local file


#### Simple data processing(transfome category data to numberic)


In [3]:

iris = pd.read_csv('Iris.csv')
df = pd.DataFrame(iris)
df = df.drop('Id', axis=1)
category_map = {
                'Species': {'Iris-setosa':1, 'Iris-versicolor':2, 'Iris-virginica':3}
                }
df_encoded = ce.category_transform(df, category_map)
print(df_encoded.describe())


       SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm     Species
count     150.000000    150.000000     150.000000    150.000000  150.000000
mean        5.843333      3.054000       3.758667      1.198667    2.000000
std         0.828066      0.433594       1.764420      0.763161    0.819232
min         4.300000      2.000000       1.000000      0.100000    1.000000
25%         5.100000      2.800000       1.600000      0.300000    1.000000
50%         5.800000      3.000000       4.350000      1.300000    2.000000
75%         6.400000      3.300000       5.100000      1.800000    3.000000
max         7.900000      4.400000       6.900000      2.500000    3.000000


#### Splits the dataset into 80% train data and 20% test data


In [4]:


train_data, test_data = sp.train_test_split(df_encoded, test_ratio=0.2)

#train_data= np.array(train_data)
#X_train, y_train = train_data[:,0:4], train_data[:,4]
test_data= np.array(test_data)
X_test, y_test = test_data[:,0:4], test_data[:,4]


In [5]:
print(X_test)
print(y_test)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]


In [11]:
y_pre = []
trees = []
for i in range(6,34):
    train_da = train_data.sample(frac=0.07, replace=False, random_state=i)
    train_da= np.array(train_da)
    X_te, y_te = train_da[:,0:4], train_da[:,4]
    # Build tree base on train_data
    tree = CART_tree.build_tree(train_da, 12, 16)
    trees.append(tree)
    # Predict test_data
    for row in X_te:
        prediction = CART_tree.predict(tree, row)
        y_pre.append(prediction)
    print("Accuracy with tree:%s" %i,accuracy_metric.accuracy_metric(y_te, y_pre))
predictions1 = []
for row in X_test:
    predictions = [CART_tree.predict(tree, row) for tree in trees]
    predictions1.append(max(set(predictions), key=predictions.count))
print("Accuracy with random forest:",accuracy_metric.accuracy_metric(y_test, predictions1))


Accuracy with tree:6 0.375
Accuracy with tree:7 0.75
Accuracy with tree:8 0.625
Accuracy with tree:9 0.375
Accuracy with tree:10 0.625
Accuracy with tree:11 0.5
Accuracy with tree:12 0.5
Accuracy with tree:13 0.375
Accuracy with tree:14 0.375
Accuracy with tree:15 0.375
Accuracy with tree:16 0.625
Accuracy with tree:17 0.125
Accuracy with tree:18 0.5
Accuracy with tree:19 0.625
Accuracy with tree:20 0.5
Accuracy with tree:21 0.375
Accuracy with tree:22 0.625
Accuracy with tree:23 0.625
Accuracy with tree:24 0.5
Accuracy with tree:25 0.25
Accuracy with tree:26 0.25
Accuracy with tree:27 0.375
Accuracy with tree:28 0.5
Accuracy with tree:29 0.5
Accuracy with tree:30 0.125
Accuracy with tree:31 0.5
Accuracy with tree:32 0.375
Accuracy with tree:33 0.5
Accuracy with random forest: 0.0


### Build tree and predict


In [1]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=20, criterion='entropy', random_state=1)

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_metric.accuracy_metric(y_test, y_pred)
print("Accuracy with sklearn RandomForestClassifier:", accuracy)


NameError: name 'X_train' is not defined