# KNN Classification Iris withoutlibrary

 #### IMPORTING LIBRARIES

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
plt.style.use('fivethirtyeight')
%matplotlib inline
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import GridSearchCV
import scipy.stats as stats
from sklearn.metrics import accuracy_score



### READ DATA

In [2]:
iris = pd.read_csv('Iris.csv')

### OVERVIEW DATA
##### We see that have
##### + 150 rows and 6 columns 
##### + 1 Categorical column and 5 Numerical
##### + No missing values.

In [3]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [4]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

### Transform species to numberic

In [5]:
le = LabelEncoder()
iris['Species'] = le.fit_transform(iris['Species'])

In [6]:
iris['Species']

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int32

### +X variable contains the attributes 
### +Y contains the labels.

In [7]:
X = iris.iloc[:, :-1].values
y = iris['Species']

### Splits the dataset into 80% train data and 20% test data

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42, stratify=y)

### Feature Scaling

In [9]:
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

### Implementation the KNN
##### Calculate the distances between a test point and all points.
##### Reshape the distances.
##### Stack the reshaped distance list.
##### Sort the train_df.
##### Take the mean of the y_train values from the first 5 rows to obtain the prediction value.
##### Repeat

#####
#####
#####

In [15]:
train = np.array(X_train)
test = np.array(X_test)
y_train = np.array(y_train)

y_train = y_train.reshape(-1, 1)

train_df = np.hstack([train, y_train])
list(train_df[0:6])

[array([-1.55163971, -1.72156775, -0.32483982, -1.34703555, -1.32016847,
         0.        ]),
 array([ 0.72984103, -1.12449223, -1.22612948,  0.41429037,  0.65186742,
         2.        ]),
 array([ 0.03142856,  1.14439475, -0.55016223,  0.58474127,  0.25746024,
         1.        ]),
 array([-1.52835929, -1.12449223,  0.12580502, -1.29021859, -1.45163753,
         0.        ]),
 array([ 0.33407397, -0.40800161, -1.22612948,  0.13020555,  0.12599118,
         1.        ]),
 array([ 1.66105766,  0.54731923, -1.22612948,  0.6983752 ,  0.91480554,
         2.        ])]

In [11]:
preds = []
for i in range(len(test)):
    distances = np.sqrt(np.sum((train - test[i])**2, axis = 1))
    distances = distances.reshape(-1,1)
    matrix = np.hstack([train_df, distances])
    sorted_matrix = matrix[matrix[:,-1].argsort()]
    neighbours = [sorted_matrix[i][-2] for i in range(5)]
    pred_value = np.mean(neighbours)
    preds.append(pred_value)
knn_scratch_pred = np.array(preds)
knn_scratch_pred


array([0., 2., 1., 1., 0., 1., 0., 0., 2., 1., 2., 2., 2., 1., 0., 0., 0.,
       1., 1., 2., 0., 2., 1., 2., 2., 1., 1., 0., 2., 0.])

### MODEL EVALUATION

In [12]:
print(confusion_matrix(y_test, knn_scratch_pred))
print(classification_report(y_test, knn_scratch_pred))

[[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [13]:
print("Accuracy : %.2f %%" %(100*accuracy_score(y_test, knn_scratch_pred)))


Accuracy : 100.00 %
